---
title: "Lexical Scoping Examples"
output:
   
  html_notebook: 
    code_folding: hide
    toc: yes
  html_document:
    theme: united
    highlight: tango
    toc: true
    toc_float:
      
      collapsed: false
---



## Ex1 - Bank Account

```{r}

## Here is a little example which shows a fundamental difference between
## R and S.  It is a little example from Abelson and Sussman which models
## the way in which bank accounts work.	It shows how R functions can
## encapsulate state information.
##
## When invoked, "open.account" defines and returns three functions
## in a list.  Because the variable "total" exists in the environment
## where these functions are defined they have access to its value.
## This is even true when "open.account" has returned.  The only way
## to access the value of "total" is through the accessor functions
## withdraw, deposit and balance.  Separate accounts maintain their
## own balances.
##
## This is a very nifty way of creating "closures" and a little thought
## will show you that there are many ways of using this in statistics.

#  Copyright (C) 1997-8 The R Core Team

open.account <- function(total) {
  
  list(
    deposit = function(amount) {
      if(amount <= 0)
        stop("Deposits must be positive!\n")
      total <<- total + amount
      cat(amount,"deposited. Your balance is", total, "\n\n")
    },
    withdraw = function(amount) {
      if(amount > total)
        stop("You don't have that much money!\n")
      total <<- total - amount
      cat(amount,"withdrawn.  Your balance is", total, "\n\n")
    },
    balance = function() {
      cat("Your balance is", total, "\n\n")
    }
  )
}

ross <- open.account(100)
robert <- open.account(200)

ross$withdraw(30)
ross$balance()
robert$balance()

ross$deposit(50)
ross$balance()

```


## Ex2 - Cacheing the mean

```{r}

# In this example we introduce the <<- operator which can be used to assign a
# value to an object in an environment that is different from the current
# environment. Below are two functions that are used to create a special object
# that stores a numeric vector and cache's its mean.
# 
# The first function, makeVector creates a special "vector", which is really a list containing a function to
# 
# set the value of the vector
# get the value of the vector
# set the value of the mean
# get the value of the mean



makeVector <- function(x = numeric()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setmean <- function(mean) m <<- mean
  getmean <- function() m
  list(set = set, get = get,
       setmean = setmean,
       getmean = getmean)
}

#The following function calculates the mean of the special "vector" created with
#the above function. However, it first checks to see if the mean has already
#been calculated. If so, it gets the mean from the cache and skips the
#computation. Otherwise, it calculates the mean of the data and sets the value
#of the mean in the cache via the setmean function.



cachemean <- function(x, ...) {
  m <- x$getmean()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- mean(data, ...)
  x$setmean(m)
  m
}

vect1<-makeVector(1:100)
cachemean(vect1)
vect1$getmean


vect1$getmean()

vect1$set(1:5)
cachemean(vect1)
cachemean(vect1)




```

